title: Waypoint Explorer
description: Report for Laboratory of Software Systems course
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
aux_links:
  Organizzazione GitHub: https://github.com/Waypoint-Explorer
search_enabled: false
