title: Waypoint Explorer LSS Report
description: Report for Laboratory of Software Systems course.
theme: just-the-docs
search_enabled: false

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
